### ISSUE TITLE
report unable to start issue

### ISSUE THREAD

**Issue by jinyugang** [o3bvv/nvidia-gpu-fan-controller#1]
![image](https://user-images.githubusercontent.com/22240643/105626003-3264ab00-5e68-11eb-9b6c-a85f937b146e.png)

I use vc2019 to complie. after compile it showing unable to start issue on dlib.lib.

**Comment by o3bvv** [comment]
You are trying to run a library. Try selecting the `gpu_reporter` project as current and run it.
